pre-release-hook = [ "cargo", "run", "--release", "--", "changelog", "--no-links", "--unreleased", "{{version}}", "-o", "CHANGELOG.md" ]
pre-release-commit-message = "chore: release v{{version}}"
tag-message = "{{crate_name}} v{{version}}"
