name: Pull request
# This workflow is triggered on pushes to the repository.
on: [ pull_request ]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install stable toolchain and check style
        run: rustup toolchain install --profile minimal nightly --component rustfmt
      - run: cargo +nightly fmt -- --check
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # A PR should not contain too many commits
          fetch-depth: 10
      - name: Validate commit messages
        run: |
          git show-ref
          curl -sSfL https://github.com/convco/convco/releases/latest/download/convco-ubuntu.zip | zcat > convco
          chmod +x convco
          ./convco check ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          rm convco
      - name: Install stable toolchain
        run: rustup toolchain install --profile minimal stable
      - name: Run tests
        run: cargo test
